//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_prayaga.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class facultad
    {
        public facultad()
        {
            this.carrera = new HashSet<carrera>();
        }
    
        public int id { get; set; }
        public string nombre_facultad { get; set; }
        public string codigo_facultad { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Nullable<System.DateTime> creado_tmstp { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public byte[] actualizado_tmstp { get; set; }
        public bool eliminado { get; set; }
        public virtual ICollection<carrera> carrera { get; set; }
    }
}
